name: maestro
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip=24
  - pip:
      - pretty-errors
      - standard-deluxe @ git+https://github.com/gravures/standard-deluxe@dev-features
variables:
